# Generated by Django 4.2.2 on 2023-06-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
